services:
  desafio_emprestimos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'desafio_emprestimos'
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: bash -c "npm install && npm run build && npm start"
networks:
  default:
    name: local
